contact_links:
  - name: Splunk Community Slack
    url: http://splk.it/slack
    about: Please ask questions in #tarunner
  - name: Splunk Community Support
    url: https://community.splunk.com/
    about: Please ask and answer questions here.
