name: SAST Scan
jobs:
  sast-scan:
    uses: splunk/sast-scanning/.github/workflows/sast-scan.yml@main
    secrets: inherit
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/semgrep.yaml'
  schedule:
    - cron: '0 0 * * 1-5' # Every weekday at midnight UTC